const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  signalTerminalReady: () => ipcRenderer.send('terminal-ready'),
  sendTerminalInput: (data) => ipcRenderer.send('terminal-input', data),
  resizeTerminal: (size) => ipcRenderer.send('terminal-resize', size),
  onTerminalData: (cb) => ipcRenderer.on('terminal-data', (_, data) => cb(data)),
  onTerminalExit: (cb) => ipcRenderer.on('terminal-exit', (_, code) => cb(code)),
  navigate: (url) => ipcRenderer.send('navigate', url),
  goBack: () => ipcRenderer.send('go-back'),
  goForward: () => ipcRenderer.send('go-forward'),
  reload: () => ipcRenderer.send('reload'),
  onUrlChanged: (cb) => ipcRenderer.on('url-changed', (_, url) => cb(url)),
  resizeSidebar: (width) => ipcRenderer.send('sidebar-resize', width),
  onCdpPort: (cb) => ipcRenderer.on('cdp-port', (_, port) => cb(port)),
  toggleSidebar: () => ipcRenderer.send('toggle-sidebar'),
  onSidebarToggled: (cb) => ipcRenderer.on('sidebar-toggled', (_, visible) => cb(visible)),
  createTab: (url) => ipcRenderer.send('create-tab', url),
  closeTab: (tabId) => ipcRenderer.send('close-tab', tabId),
  switchTab: (tabId) => ipcRenderer.send('switch-tab', tabId),
  reorderTab: (tabId, newIndex) => ipcRenderer.send('reorder-tab', tabId, newIndex),
  reopenClosedTab: () => ipcRenderer.send('reopen-closed-tab'),
  duplicateTab: (tabId) => ipcRenderer.send('duplicate-tab', tabId),
  closeOtherTabs: (tabId) => ipcRenderer.send('close-other-tabs', tabId),
  closeTabsToRight: (tabId) => ipcRenderer.send('close-tabs-to-right', tabId),
  pinTab: (tabId) => ipcRenderer.send('pin-tab', tabId),
  unpinTab: (tabId) => ipcRenderer.send('unpin-tab', tabId),
  showTabContextMenu: (tabId) => ipcRenderer.send('tab-context-menu', tabId),
  getTabs: () => ipcRenderer.invoke('get-tabs'),
  onTabsChanged: (cb) => ipcRenderer.on('tabs-changed', (_, data) => cb(data)),
  queryOmnibar: (query) => ipcRenderer.invoke('omnibar-query', query),
  omnibarVisibility: (visible) => ipcRenderer.send('omnibar-visibility', visible),
  showOmnibarPopup: (results, selectedIndex) => ipcRenderer.send('omnibar-show-popup', results, selectedIndex),
  onOmnibarSelected: (cb) => ipcRenderer.on('omnibar-selected', () => cb()),
  // Find in page
  findInPage: (text) => ipcRenderer.send('find-in-page', text),
  findNext: (forward) => ipcRenderer.send('find-next', forward),
  findClose: () => ipcRenderer.send('find-close'),
  onFindResults: (cb) => ipcRenderer.on('find-results', (_, data) => cb(data)),
  onShowFindBar: (cb) => ipcRenderer.on('show-find-bar', () => cb()),
  // Zoom
  onZoomChanged: (cb) => ipcRenderer.on('zoom-changed', (_, percent) => cb(percent)),
  // Downloads
  onDownloadProgress: (cb) => ipcRenderer.on('download-progress', (_, data) => cb(data)),
  onDownloadDone: (cb) => ipcRenderer.on('download-done', (_, data) => cb(data)),
  downloadCancel: (id) => ipcRenderer.send('download-cancel', id),
  downloadOpen: (id) => ipcRenderer.send('download-open', id),
  downloadShow: (id) => ipcRenderer.send('download-show', id),
  // Status bar
  onStatusBarUrl: (cb) => ipcRenderer.on('status-bar-url', (_, url) => cb(url)),
  // Fullscreen
  onFullscreenChanged: (cb) => ipcRenderer.on('fullscreen-changed', (_, isFs) => cb(isFs)),
});
